import React, { HTMLInputTypeAttribute } from 'react';
import { SingleValue } from 'react-select';
import { SelectOption } from '../SelectItem/SelectItem';
declare type SelectInputProps = {
    name: string;
    className?: string;
    label?: string;
    labelClass?: string;
    options?: SelectOption[];
    placeholder?: string;
    inputPlaceholder?: string;
    onSelectChange?: (opt: SingleValue<SelectOption>) => void;
    onInputChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
    selectDefaultValue?: SelectOption;
    selectValue?: SelectOption;
    inputDefaultValue?: string;
    inputValue?: string;
    inputType?: HTMLInputTypeAttribute;
    inputMin?: number;
    inputMax?: number;
    searchable?: boolean;
    required?: boolean;
    disabled?: boolean;
    disabledSelect?: boolean;
    reverse?: boolean;
    error?: string;
};
declare const SelectInput: React.FC<SelectInputProps>;
export default SelectInput;
