import React from 'react';
import { SingleValue } from 'react-select';
import { SelectOption } from '../SelectItem/SelectItem';
declare type SelectInputProps = {
    name: string;
    className?: string;
    label?: string;
    labelClass?: string;
    options?: SelectOption[];
    placeholder?: string;
    inputPlaceholder?: string;
    onSelectChange?: (opt: SingleValue<SelectOption>) => void;
    onInputChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
    defaultValue?: SelectOption;
    inputDefaultValue?: string;
    searchable?: boolean;
    required?: boolean;
    disabled?: boolean;
    reverse?: boolean;
};
declare const SelectInput: React.FC<SelectInputProps>;
export default SelectInput;
