import { createTheme } from '@mui/material/styles';
import { tokens } from '../../theme/tokens';
import { buttonVariants } from './button/variants';

const muiTheme = createTheme({
  typography: {
    fontFamily: ['Inter', 'GT Super Text', 'sans-serif'].join(','),
    // text
    headline_ss_xxl: tokens.typography.headline_ss_xxl,
    headline_ss_xl: tokens.typography.headline_ss_xl,
    headline_ss_l: tokens.typography.headline_ss_l,
    headline_ss_m: tokens.typography.headline_ss_m,
    headline_ss_s: tokens.typography.headline_ss_s,
    headline_ss_xs: tokens.typography.headline_ss_xs,
    headline_ss_xxs: tokens.typography.headline_ss_xxs,
    headline_xxl: tokens.typography.headline_xxl,
    headline_xl: tokens.typography.headline_xl,
    headline_l: tokens.typography.headline_l,
    headline_m: tokens.typography.headline_m,
    headline_s: tokens.typography.headline_s,
    body_xl: tokens.typography.body_xl,
    body_l: tokens.typography.body_l,
    body_m: tokens.typography.body_m,
    body_s: tokens.typography.body_s,
    text_link_m: tokens.typography.text_link_m,
    text_link_s: tokens.typography.text_link_s,
    caption: tokens.typography.caption,
    h1: undefined,
    h2: undefined,
    h3: undefined,
    h4: undefined,
    h5: undefined,
    h6: undefined,
    subtitle1: undefined,
    subtitle2: undefined,
    body1: undefined,
    body2: undefined,
    button: undefined,
    overline: undefined,
  },
  palette: {
    primary: {
      shade: tokens.colors.shade,
      light: tokens.colors.primary400,
      main: tokens.colors.primary500,
      dark: tokens.colors.primary600,
      400: tokens.colors.primary400,
      500: tokens.colors.primary500,
      600: tokens.colors.primary600,
      contrastText: tokens.colors.accent,
    },
    secondary: {
      main: tokens.colors.black,
      contrastText: tokens.colors.white,
    },
    accent: {
      main: tokens.colors.accent,
      contrastText: tokens.colors.primary500,
    },
    grey: {
      50: tokens.colors.grey50,
      100: tokens.colors.grey100,
      200: tokens.colors.grey200,
      300: tokens.colors.grey300,
      400: tokens.colors.grey400,
      500: tokens.colors.grey500,
      600: tokens.colors.grey600,
      700: tokens.colors.grey700,
      800: tokens.colors.grey800,
      900: tokens.colors.grey900,
    },
    warning: {
      100: tokens.colors.warning100,
      200: tokens.colors.warning200,
      300: tokens.colors.warning300,
      400: tokens.colors.warning400,
      500: tokens.colors.warning500,
      600: tokens.colors.warning600,
      700: tokens.colors.warning700,
    },
    error: {
      100: tokens.colors.error100,
      200: tokens.colors.error200,
      300: tokens.colors.error300,
      400: tokens.colors.error400,
      500: tokens.colors.error500,
      600: tokens.colors.error600,
      700: tokens.colors.error700,
    },
    info: {
      100: tokens.colors.info100,
      200: tokens.colors.info200,
      300: tokens.colors.info300,
      400: tokens.colors.info400,
      500: tokens.colors.info500,
      600: tokens.colors.info600,
      700: tokens.colors.info700,
    },
    whiteScale: {
      100: tokens.colors.white100,
      200: tokens.colors.white200,
      300: tokens.colors.white300,
      400: tokens.colors.white400,
      500: tokens.colors.white500,
      600: tokens.colors.white600,
      700: tokens.colors.white700,
      800: tokens.colors.white800,
    },
  },
  components: {
    MuiTypography: {
      defaultProps: {
        variantMapping: {
          // Map the new variant to render a <h1> by default
          headline_ss_xxl: 'h1',
          headline_ss_xl: 'h2',
          headline_ss_l: 'h3',
          headline_ss_m: 'h4',
          headline_ss_s: 'h5',
          headline_ss_xs: 'h6',
          headline_ss_xxs: 'h6',
          headline_xxl: 'h1',
          headline_xl: 'h2',
          headline_l: 'h3',
          headline_m: 'h4',
          headline_s: 'h5',
          body_xl: 'p',
          body_l: 'p',
          body_m: 'p',
          body_s: 'p',
          text_link_m: 'span',
          text_link_s: 'span',
          caption: 'span',
        },
      },
    },
    MuiButton: {
      styleOverrides: {
        disableElevation: true,
      },
      variants: buttonVariants,
    },
  },
});

export { muiTheme };
